name: Check Python Dependency Conflicts

on:
  pull_request:
    branches:
      - main

jobs:
  dependency-conflict-check:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check for dependency conflicts
        run: pip check
